print("    @@@@@@@@@@@@@@@     @    @@@@@@@@@@@     @")
print("    @                   @    @               @")
print("    @                   @    @               @")
print("    @                   @    @               @")
print("    @    @@@@@@@@@      @    @@@@@@@@@@@     @")
print("    @            @      @    @               @")
print("    @            @      @    @               @")
print("    @            @      @    @               @")
print("    @@@@@@@@@@@@@@      @    @@@@@@@@@@@     @@@@@@@@@@@@@")
print('Dia berkata, "Tolong peluk dia <3"')
print(' i`m busy ')
